field: 5b38c854-547f-439a-8199-6e877bb9d441 # Post Content
fieldLayouts:
  dcf8dc4e-d77c-4c50-a71c-28eca33287f4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bd79f829-30d4-4eb2-8823-57349922fbfb # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: add4d849-dfc6-44ba-a96a-853096b0e621
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 99fba622-84f5-49a6-9719-fdb6246e6093 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be4cd103-6dac-449a-a045-7e68e1fa643f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b0836dc-fbe5-415d-8de9-006fcb02e47a
        userCondition: null
fields:
  99fba622-84f5-49a6-9719-fdb6246e6093: # Text
    columnSuffix: dlythmgr
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: true
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  bd79f829-30d4-4eb2-8823-57349922fbfb: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:1b1e14ec-db1b-4232-90e4-cc29ab20ff8e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:1b1e14ec-db1b-4232-90e4-cc29ab20ff8e' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: text
name: Text
sortOrder: 1
