fieldLayouts:
  490629c8-1553-4c37-a7fb-6d88c833333c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 11db298d-619a-4c7d-a5d3-5ce25a244bda # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e321b40-ef61-4b34-83b5-18945fc3f6f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f78e5602-51c6-4a84-9dd2-59cdae801557 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e82c8f33-7ea4-4ccf-b9b0-608b3a1d2103
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5b38c854-547f-439a-8199-6e877bb9d441 # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddffe8c1-4d76-498e-a3af-1c52c7af8751
            userCondition: null
            warning: null
            width: 100
        name: Blog
        uid: 58f81dfc-e877-48e7-8e1e-a29f57c7bffe
        userCondition: null
handle: blog
hasTitleField: true
name: Blog
section: e57fe10e-a49e-4330-9f90-5c1c4c4d39a8 # blog
sortOrder: 1
titleFormat: Title
titleTranslationKeyFormat: null
titleTranslationMethod: site
