columnSuffix: null
contentColumnType: string
fieldGroup: dc122da5-1d32-475c-ae4b-dbb9d2f1e2e7 # Common
handle: postContent
instructions: 'The content of this post or page.'
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
