defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  fd82a56c-a7be-4867-9883-1b9734398820: # Cafric
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
